language: ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0

sudo: false

# we need a more recent cmake than travis/linux provides (at least 2.8.9):
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

cache: bundler
git:
  depth: 10
